### ISSUE TITLE
Create mock server

### ISSUE THREAD

**Issue by chimon2000** [OpenCLTBrigade/community-events#14]
**Is your feature request related to a problem? Please describe.**
We need a way for frontend developers to build the website w/o relying on the API

**Describe the solution you'd like**
Create a mock API server that can serve up fake events.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by KingPra** [comment]
I'd like to jump on this. Do you have any guidelines or recommendations for getting started?

**Comment by AndrewNatoli** [comment]
Resolved by #18
